version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      # specify the version you desire here
      # - image: circleci/php:7.0-fpm-node-browsers
      - image: k1sul1/circleci-wordpress:0.0.1
        environment:
          - WP_TEST_URL: "http://localhost:1200"
          - WP_TEST_USER: "test"
          - WP_TEST_USER_PASS: "test"
          - WP_ENV: "ci"
          - MYSQL_ALLOW_EMPTY_PASSWORD: true,
          - MYSQL_DATABASE: "circle_test"
          - MYSQL_HOST: "127.0.0.1"
          - DB_HOST: "127.0.0.1"
          - DB_USER: "root"
          - DB_PASSWORD: ""
          - DB_NAME: "circle_test"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}

            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Composer install
          command: composer install --quiet

      - run:
          name: Install WPCLI
          command: |
            # set +eo pipefail
            # set -x
            # Get WP-cli
            echo "memory_limit = 512M" | sudo -E tee --append /usr/local/etc/php/conf.d/docker-php-memory.ini
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            chmod +x wp-cli.phar
            sudo mv wp-cli.phar /usr/local/bin/wp

      - run:
          name: Verify WP Core Files
          command: ls -lah wordpress

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

  deploy:
    working_directory: ~/repo
    docker:
      - image: k1sul1/circleci-wordpress:0.0.1
    steps: 
      - checkout
      - restore_cache:
          keys: 
          - v1-dependencies-{{ checksum "composer.json" }}
      - run:
          name: Composer install
          command: composer install --quiet
      - run:
          name: Check Files
          command: ls -lah wordpress
      - add_ssh_keys
      - run:
          name: Test ssh connection
          command: ssh $SERVER_USER@$SERVER_HOST -o StrictHostKeyChecking=no  "whoami"
      - run:
          name: Sync Files
          command: rsync -avz wordpress/ $SERVER_USER@$SERVER_HOST:$DEPLOY_PATH


workflows:
  version: 2
  build-deploy:
    jobs:
      # - build
      - deploy:
          requires:
            # - build