version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      # specify the version you desire here
      # - image: circleci/php:7.0-fpm-node-browsers
      - image: k1sul1/circleci-wordpress:0.0.1
        environment:
          - WP_TEST_URL: "http://localhost:12000"
          - WP_TEST_USER: "test"
          - WP_TEST_USER_PASS: "test"
          - WP_ENV: "ci"
          - MYSQL_ALLOW_EMPTY_PASSWORD: true,
          - MYSQL_DATABASE: "circle_test"
          - MYSQL_HOST: "127.0.0.1"
          - DB_HOST: "127.0.0.1"
          - DB_USER: "root"
          - DB_PASSWORD: ""
          - DB_NAME: "circle_test"

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mysql:5.7.22-ram

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}

            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Composer install
          command: composer install

      - run:
          name: Install WPCLI
          command: |
            # set +eo pipefail
            # set -x
            # Get WP-cli
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            chmod +x wp-cli.phar
            sudo mv wp-cli.phar /usr/local/bin/wp
      - run:
          name: Install PHP Alt Router
          command: |
            # Get alternative router
            cd ~/repo/wordpress
            curl -s https://raw.githubusercontent.com/Seravo/wordpress-test-template/master/lib/router.php > router.php
            ls
            php -S 0.0.0.0:8080 router.php &
            sleep 2; # This randomly fixed issue with not being able to connect
            curl -i http://localhost:8080
      - run:
          name: Install WP Core
          command: |
            cd ~/repo/wordpress
            ls wordpress/wp-content/plugins
            wp config create --dbname=$DB_NAME --dbuser=$DB_USER --dbpass=$DB_PASS --dbhost=$DB_HOST --allow-root
            wp core install --url=$WP_TEST_URL --title="CI Build Site" --admin_user=$WP_TEST_USER --admin_email=admin@example.com --admin_password=$WP_TEST_USER_PASS --skip-email --allow-root
            wp rewrite structure '/%postname%/' --allow-root
            wp plugin activate static-html-output-plugin --allow-root

      - run:
          name: Customize WP Posts
          command: |
            cd ~/repo/wordpress
            wp post delete $(wp post list --field=ID --format=csv --post_type=post,page --allow-root) --allow-root
            HOME_PAGE_ID=$(wp post create --post_author=1 --post_date=2019-11-13 --post_title="WordPress Static Deployment"  --post_status=publish --post_type=page --comment_status=closed --post_modified=2019-11-13 --porcelain --allow-root ../static-content/homepage.md)
            wp option set show_on_front page --allow-root
            wp option set page_on_front $HOME_PAGE_ID --allow-root
            wp post meta update $HOME_PAGE_ID _is_githuber_markdown 1 --allow-root
      - run:
          name: Set wp2static settings
          command: |
            wp wp2static options set debug_mode 1 --allow-root
            wp wp2static options set detection_level homepage --allow-root
            wp wp2static options set selected_deployment_option zip --allow-root
            wp wp2static options set baseUrl https://rfair404.github.io/wp-static-deploy --allow-root
            wp wp2static options set baseUrl-zip https://rfair404.github.io/wp-static-deploy --allow-root
      - run:
          name: Crawl site with wp2static
          command: |
            wp wp2static options set debug_mode 1 --allow-root

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

workflows:
  version: 2
  build-deploy:
    jobs:
      - build