version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/php:7.2-fpm-node-browsers
        environment:
          - WP_TEST_URL: "http://localhost:1200"
          - WP_TEST_USER: "test"
          - WP_TEST_USER_PASS: "test"
          - WP_ENV: "ci"
          - MYSQL_ALLOW_EMPTY_PASSWORD: true,
          - MYSQL_DATABASE: "circle_test"
          - MYSQL_HOST: "127.0.0.1"
          - DB_HOST: "127.0.0.1"
          - DB_USER: "root"
          - DB_PASSWORD: ""
          - DB_NAME: "circle_test"

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run:
          name: Create Composer Auth
          command: | 
            cp auth-sample.json auth.json
            sed -i 's/KEY_HERE/'"$COMPOSER_AUTH_KEY"'/g' auth.json
            sed -i 's/PASS_HERE/'"$COMPOSER_AUTH_PASSWORD"'/g' auth.json
      - run:
          name: Composer install
          command: composer install

      - run:
          name: Install WPCLI
          command: |
            # set +eo pipefail
            # set -x
            # Get WP-cli
            echo "memory_limit = 512M" | sudo -E tee --append /usr/local/etc/php/conf.d/docker-php-memory.ini
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            chmod +x wp-cli.phar
            sudo mv wp-cli.phar /usr/local/bin/wp

      - run:
          name: Verify WP Core Files
          command: ls -lah wordpress

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
  deploy-dev:
    working_directory: ~/repo
    docker:
      - image: circleci/php:7.2-fpm-node-browsers
    steps:
      - checkout      
      - run:
          name: Create Composer Auth
          command: | 
            cp auth-sample.json auth.json
            sed -i 's/KEY_HERE/'"$COMPOSER_AUTH_KEY"'/g' auth.json
            sed -i 's/PASS_HERE/'"$COMPOSER_AUTH_PASSWORD"'/g' auth.json
      - run:
          name: Composer install
          command: composer install
      - run:
          name: Authenticate Terminus Connection
          command: vendor/bin/terminus auth:login --machine-token=$TERMINUS_AUTH_KEY
      - run:
          name: Check Terminus Site Info
          command: vendor/bin/terminus site:info $PANTHEON_SITE.dev

  deploy-prod:
    working_directory: ~/repo
    docker:
      - image: circleci/php:7.2-fpm-node-browsers
    steps: 
      - checkout
      - restore_cache:
          keys: 
          - v1-dependencies-{{ checksum "composer.json" }}
      - run:
          name: Create Composer Auth
          command: | 
            cp auth-sample.json auth.json
            sed -i 's/KEY_HERE/'"$COMPOSER_AUTH_KEY"'/g' auth.json
            sed -i 's/PASS_HERE/'"$COMPOSER_AUTH_PASSWORD"'/g' auth.json
      - run:
          name: Composer install
          command: composer install --quiet
      - run:
          name: Check Files
          command: ls -lah wordpress
      - add_ssh_keys


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
          filters:
          # branches:
            ignore: 
              - master
      - deploy-prod:
          requires:
            - build
          # filter:
          branches:
            only: 
              - master